# Generated by Django 3.2.9 on 2021-11-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('searchfield', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'inventoryapp_item',
                'ordering': ['code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'inventoryapp_store',
                'ordering': ['code'],
                'managed': False,
            },
        ),
    ]
