# Generated by Django 3.2.9 on 2021-11-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationCode', models.CharField(max_length=20)),
                ('Quantity', models.FloatField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventoryapp.item')),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventoryapp.store')),
            ],
            options={
                'unique_together': {('Item', 'LocationCode', 'Store')},
            },
        ),
    ]
