# Generated by Django 3.2.9 on 2021-11-29 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationCode', models.CharField(blank=True, max_length=20)),
                ('Quantity', models.FloatField()),
                ('InputDate', models.DateTimeField(default=datetime.datetime(2021, 11, 29, 13, 46, 15, 879514))),
                ('InputUser', models.IntegerField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventoryapp.item')),
                ('Store', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.DO_NOTHING, to='inventoryapp.store')),
            ],
            options={
                'unique_together': {('Store', 'Item'), ('Item', 'LocationCode', 'Store')},
            },
        ),
    ]
