# Generated by Django 3.2.9 on 2021-11-29 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='InputDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 13, 46, 18, 757408)),
        ),
    ]
