# Generated by Django 3.2.9 on 2021-11-25 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='InputDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 15, 31, 36, 974891)),
        ),
        migrations.AddField(
            model_name='stock',
            name='InputUser',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
